const USER_TYPE = {
    ADMIN: 1,
    STUDENT: 2,
    SUPERVISOR: 3,
    PANEL_MEMBER: 4,
}

const STATUS_TYPE = {
    WAITING_FOR_APPROVAL: 1,
    ACCEPTED: 2,
    REJECTED: 3
}

const REQUEST_TYPE = {
    TOPIC_REGISTRATION: 1,
    CO_SUPERVISOR_REGISTRATION: 1,
}

const SUBMISSION_TYPE = {
    TOPIC_EVALUATION: 1,
    PROJECT_PROPOSAL_PRESENTATION: 2,
    FINAL_THESIS: 3
}

const JWT_TOKEN = 'SlIIt2022@ToKen'

module.exports = {
    USER_TYPE: USER_TYPE,
    JWT_TOKEN: JWT_TOKEN,
    STATUS_TYPE: STATUS_TYPE,
    REQUEST_TYPE: REQUEST_TYPE,
    SUBMISSION_TYPE: SUBMISSION_TYPE
}